### ISSUE TITLE
Is this gem actively maintained/valid replacement over databasedotcom?

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [restforce/restforce#155]
Sorry to bother you with this, I'm thinking about replacing databasedotcom due to various issues with their design (can't force an HTTP authentication request, also when a new access token is obtained with refresh token, it's not stored, actually refreshing the token **each time**, with an additional request. And no simple way to actually get a new access token with current refresh token).

What I would like to know is if this gem it's a valid replacement over databasedotcom.
Considering this was updated 4 days ago (while databasedotcom 2 years ago), I definitely believe this is a better choice, but maybe there are well-known issues that makes this unusable which I'm not aware of.
I'll perform mostly REST operations on salesforce and expecially handling the connection part (I already had oauth login working with databasedotcom), considering I'll be using mostly the salesforce_bulk_api gem for bulk operations (anything "bigger" than 1 record basically).

**Comment by msreekm** [comment]
I don't think databasedotcom gem is maintained actively. I posted an issue/question and no response.Switched to restforce since then.,
