### ISSUE TITLE
Server errors at random

### ISSUE THREAD

**Issue by marcelloma** [restforce/restforce#156]
Hi,

I keep getting these errors at random.

Faraday::Error::ClientError: SERVER_UNAVAILABLE: Server too busy
Faraday::Error::ConnectionFailed: end of file reached
Faraday::Error::TimeoutError: Net::ReadTimeout

Overall communication with salesforce's seem a little bit slower than it should be. Have anybody ever experienced this while using Restforce?

Thanks in advance!

**Comment by axmav** [comment]
@marcelloma I understand that it was a long time ago, but maybe you still remember what the problem was?
