### ISSUE TITLE
Faraday::ResourceNotFound: NOT_FOUND: The requested resource does not exist

### ISSUE THREAD

**Issue by KMontag42** [restforce/restforce#160]
I get this error on every call I make using Restforce.

Any ideas?

It was working fine the last time I dove into Salesforce (about a week ago)

**Comment by wmadden** [comment]
I'm having this error too and don't know how to debug it

**Comment by wmadden** [comment]
I found the problem, I had passed `api_version: 38` instead of `api_version: "38.0"`. This error is really really unhelpful.

**Comment by cmalpeli** [comment]
@wmadden thanks for this - I had done the same thing - you just saved me a ton of time.

**Comment by wmadden** [comment]
Glad I could help, @cmalpeli :)

**Comment by timrogers** [comment]
@wmadden Thanks for the warning about this! Will look at implementing something to warn people :heart:

**Comment by msaffitz** [comment]
👍  Ran into this as well.  Thanks for the heads up.

**Comment by erlandsona** [comment]
Just ran into this same thing with v40... I had `'40'` in my initializer but needed `'40.0'` Thanks!

**Comment by timrogers** [comment]
This reminds me to look at adding a warning! Thanks for the bump ❤️

**Comment by calasyr** [comment]
I estimate the loss to the global economy caused by incredibly vague Salesforce error message to be in the hundreds of millions of dollars.
