### ISSUE TITLE
Errno::ENAMETOOLONG when calling client.describe_layouts('Object_name','Record Type')

### ISSUE THREAD

**Issue by huwd** [restforce/restforce#221]
Hey, 

I keep getting an error when calling `client.describe_layouts('Object_name','Record Type')`... not sure if there's a limit to the method that i'm not seeing?

`Errno::ENAMETOOLONG: File name too long @ rb_sysopen - /home/ubuntu/workspace/myapp/tmp/cache/%2Fservices%2Fdata%2Fv34.0%2Fsobjects%2FMy_Object__c%2Fdescribe%2Flayouts%BLAHBLAHBLAHBLAHBLAHBLAH%BLAHBLAHBLAHBLAHBLAHBLAHETCETCETCETCETC-errorcodegoesonforages`

As it's pointing to `/tmp/cache` i thought it may be because the layout i'm trying to draw on is very large and clogging the cache but when I wrap my code in `.without_cache` as per below I still get the same issue...

``` Ruby
def grab_all_layouts
  restforce = Restforce.new # treat as same as client. in README.md docs
  list_of_objects # Has all my object variables within

  list_of_objects.each do | object |
    object_api_name = object.api_name
    object_rec_type = object.content.RecordTypeId
    restforce.without_caching do
     sample_layout = restforce.describe_layouts(object_api_name,object_rec_type).layouts.first["detailLayoutSections"]
    end
  end
  sample_layout
end
```

The method will return some layouts but promptly throw the above error on others, I can't clearly see what any commonality would be, they're all just layouts, all accessible via https://workbench.developerforce.com.

Is there a limit to what restforce can parse somewhere on layouts or am i doing something stupid?

Perhaps is there a verbose return so I can see how far the request is getting - and then where it all goes south?

**Comment by timrogers** [comment]
@huwd Sorry - I missed this one! Did you work out what was going on here?

**Comment by timrogers** [comment]
@huwd The "cache key", which here is too long, is generated by https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/response/caching.rb#L61. Clearly it's ending up being too long - maybe we could make the key more sensible somehow - but there appears to be a broader problem if it's ignoring `without_caching`. Have you done any more investigation?

**Comment by timrogers** [comment]
I've made an issue at https://github.com/lostisland/faraday_middleware/issues/132 too.

**Comment by huwd** [comment]
Hi Tim,

My apologies for letting this slide, I did end up removing restforce caching from where i define `Restforce.new` which does prevent the issue cropping up. Not as massive problem as I'm still not making much of a dent in my daily limits, but I guess caching would be nice to re-enable at some point.

What am I doing to be getting this problem? I can't be the only restforce user trying to cache?

**Comment by timrogers** [comment]
The issue is to do with the generated cache key being too long - my guess is you're passing quite long parameters to `#describe_layouts` which are used to generate the key, and this causes the problem.

One solution that would probably work is using a different caching engine - see https://github.com/ejholmes/restforce#caching. At the moment, it's trying to store in a file with a name that's too long. You might be able to use some other kind of caching?
