### ISSUE TITLE
Replay PushTopic Streaming Events (Beta)

### ISSUE THREAD

**Issue by kris-luminar** [restforce/restforce#237]
SalesForce has a new feature for PushTopics that will allow replaying events that where missed by clients.
https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/replay_pushtopic_events.htm

My team thinks that this feature only exists in version 36 of SalesForce's API. 

This feature would be very helpful for my team. Are there any plans to support this new functionality?

**Comment by anacaet** [comment]
Someone has an updates on this topic?

**Comment by panozzaj** [comment]
I implemented something that might work for this, I invite you to check out PR #265 and leave any feedback or comments.
