### ISSUE TITLE
Create and update issue

### ISSUE THREAD

**Issue by hm-mkim** [restforce/restforce#288]
Hi, I am having trouble creating and updating new contacts/accounts into salesforce. I have no issue querying and getting all the contacts however. What would you suggest?

**Comment by timrogers** [comment]
Can you explain what's going wrong? What exactly are you trying to do, and
what error do you get?

**Comment by hm-mkim** [comment]
Hey Tim,

Thanks for responding! Well, I don’t think I’m getting an error per say, but the create/update method won’t make any changes in my salesforce contacts. Below is my create method.

def create
    if current_user
      client = Restforce.new :oauth_token => current_user.oauth_token,
        :refresh_token => current_user.refresh_token,
        :instance_url  => current_user.instance_url,
        :client_id     => ENV[‘SF_CLIENT_ID’],
        :client_secret => ENV[‘SF_CLIENT_SECRET’],,
        :authentication_callback => Proc.new { |x| Rails.logger.debug x.to_s },
        :api_version => '38.0'
    end

    @contact = client.create(
      "Contact",
      Name: params[:contact][:name],
      Email: params[:contact][:email]
    )
    redirect_to contacts_path
  end







Started POST "/contact" for ::1 at 2017-02-03 11:52:24 -0800
Processing by ContactsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"rJ6SJL32s/sAvk5p4/UGJRBphZQcFXdvvKU9AHtlp3VG66BMMt/VbCGiWcUUasAMoSOSW62miX6Fj060uBoRJA==", "contact"=>{"name"=>"Jack Kings", "email"=>"jackking@example.com", "id"=>"0034100000Hhg1YAAR"}, "button"=>""}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
No template found for ContactsController#update, rendering head :no_content
Completed 204 No Content in 3380ms (ActiveRecord: 0.2ms)

**Comment by timrogers** [comment]
Can you try swapping it for `create!`? That way, it'll raise an exception to tell you what has gone wrong.

**Comment by hm-mkim** [comment]
Hey Tim,

I just tried swapping to “create!” and this is the response I get:

Faraday::ClientError in ContactsController#create
INVALID_FIELD_FOR_INSERT_UPDATE: Unable to create/update fields: Name. Please check the security settings of this field and verify that it is read/write for your profile or permission set.


Is this because my account doesn’t have permission to create?

Thanks!

**Comment by timrogers** [comment]
Yes, that's most likely the problem!

**Comment by hm-mkim** [comment]
Thanks!
