### ISSUE TITLE
INVALID_SESSION_ID: Session expired or invalid /  invalid_grant: inactive user

### ISSUE THREAD

**Issue by CroustyPopz** [restforce/restforce#303]
Hi !

I'm using your gem with omniauth-salesforce for some of my clients but it's often happening together these errors  :
  - Restforce::UnauthorizedError: INVALID_SESSION_ID: Session expired or invalid
  - Restforce::AuthenticationError: invalid_grant: inactive user

I already worked on invalid_session_id error and I'm thinking I did all rights about it (configuration & token)
But I didn't find where come from the second in this github or force documentation :/ (I supposed it's just about some of my client's desactivate/deleted account).

Thanks !

**Comment by antwonlee** [comment]
It might be similar to this issue? https://github.com/ejholmes/restforce/issues/284

**Comment by CroustyPopz** [comment]
It doesn't seems to be similar. As I said I already worked on INVALID_SESSION_ID and all work well on my side but some of my users seems to have errors :/

**Comment by antwonlee** [comment]
Gotcha.  Assuming your Users are obviously active users, I am trying to troubleshoot with you.  Do these Users have limited login hours on Salesforce side or haven't been active for a while?  What are some thing you tried so far?
