### ISSUE TITLE
How can I download a rich text image?

### ISSUE THREAD

**Issue by teezz** [restforce/restforce#344]
In Salesforce I store images in a rich text field. The image URL is stored in a separate text field (img_url =  https://XXX.content.force.com/servlet/rtaImage?eid=a0X..eoid=00N...&refid=0EM...A) and a 3rd formula field is creating an img src (e.g. img_formular = <img src=\"https://xxx.content.force.com/servlet/rtaImage?eid=a0X6E0000004YIc&amp;feoid=00N6E000000jv9g&amp;refid=0EM6E0000008U7g\" alt=\"Contact Image\" style=\"height:200px; width:200px;\" border=\"0\"/>"). In my rails app I can display that image by just adding ".html_safe" to the img_ formula field. Unfortunately I found no way how I can download the raw image file. I tried:
- image = client.get(img_url)
- File.open("#{Rails.root}//tmp/image.jpg", 'wb') { |f| f.write(image.body) }
This stores only a corrupt file. Do I miss something?

**Comment by timrogers** [comment]
Is the URL in the `img_url` field publicly accessible? (e.g. if you copy and paste it into a browser, does it work?)

**Comment by teezz** [comment]
Hi timrogers,
if I copy the img_url to another window in the same browser as the rails app it works. If I copy to another browser version it asks for login. That makes sense. But I don't find an option in Salesforce 
where I can set the img_url Textfield publicly accessible. Is that possible? (I know that option only when uploading a document).
I want to download the image in a controller action in the rails app and load it into a xmlsx file. If I try client.get(img_url) in the controller it returns something like "<Faraday::Response:0x007fc6b9e142b8 @on_complete_callbacks=[]...".

**Comment by antwonlee** [comment]
@teezz If your assets are stored as Salesforce files, you might have to make the images externally accessible.  Perhaps, it is not the field level security but the file itself is not publicly sharable.

I have similar structure but my image_url is hosted in Contentful or AWS where image sharing settings are managed as public.

If you test it with a public accessible image, your code should work fine.
