### ISSUE TITLE
Is it possible to invoke SF's fuzzy matching logic in queries?

### ISSUE THREAD

**Issue by Arepo** [restforce/restforce#347]
We have a fuzzy company name matching rule as described here: https://help.salesforce.com/articleView?id=matching_rules_matching_methods.htm&type=0

So if, having initialised our `client` object, we have, say a SF record for `Weyland-Yutani Inc` and we call `client.create!('Account', Name: 'Weyland-Yutani')`, we get this error:

```Faraday::ClientError: DUPLICATES_DETECTED: You're creating a duplicate record. We recommend you use an existing record instead.```

(which is the behaviour we want, except that it doesn't tell us the ID(s) of the existing record(s))

But this leads to issues when we try and implement find_or_create logic along these lines:

```company = client.query("Select Id from Account where Name = 'Weyland-Yutani'").first
company ||= client.create!('Account', Name: 'Weyland-Yutani')
```

(in practice we have a bit of error handling here, but it doesn't solve the underlying problem of having two inconsistent ways of determining duplicate records)

So per the issue title, is it possible to either a) invoke the fuzzy logic that the #create! method relies on when searching for a record, or b) send the ID of any duplicates back when #create! (or  #create) fails?

**Comment by timrogers** [comment]
Can you try setting `Restforce.log = true` and then looking at what is logged when you try to create a duplicate? I'm wondering if Salesforce will include in the response the clashing record. `Restforce::Middleware::Logger` will dump the request and response to STDOUT automatically.

**Comment by Arepo** [comment]
Apparently they don't :\

```body: "[{\"message\":\"You're creating a duplicate record. We recommend you use an existing record instead.\",\"errorCode\":\"DUPLICATES_DETECTED\",\"fields\":[]}]"```

I guess that means it's not possible?

**Comment by antwonlee** [comment]
@Arepo This is an interesting problem.  I don't think neither a) or b) is possible.  Perhaps, you might have to find an alternate approach to manage duplicate during `create!`. 

Can you just query the find the first, and if it returns some values have the user decided if they need to create a new record or use the returned record.  So the final logic decision is made by the user than a method.

**Comment by Arepo** [comment]
@antwonlee I'm not sure what you mean by finding the values. As far as I can see, there's no reliable way to know what the duplicate record would be (short of trying to duplicate the whole fuzzy match logic), since we just get the text above back. So all we could say to the users is 'we think there's a similar record with slightly different details - do you want to try changing your details until we stop bugging you with this message?' which doesn't feel like a great UX :P

**Comment by timrogers** [comment]
My googling seems to imply that it's not currently possible to get what
you're looking for in the REST API, unfortunately. You also can't customise
the application of these kinds of rules, as you can in the SOAP API with
headers (see https://success.salesforce.com/ideaView?id=0873A000000lEL5QAM).

One suggestion is to implement your own REST endpoint in Apex, which could
have this functionality - see
https://salesforce.stackexchange.com/questions/66050/duplicate-matching-rules-via-rest-api/66926#66926
.

**Comment by Arepo** [comment]
Thanks Tim. That's probably a heavier touch than we want atm for what's a pretty rare edge case, so I guess we can shelve this issue.
