### ISSUE TITLE
Custom fields will not update

### ISSUE THREAD

**Issue by LucasCioffi** [restforce/restforce#353]
Great gem, by the way!

Is there a way to set the permissions with the tooling API at the moment the custom field is created?

I'm able to create a custom field using the tooling API:
```
@salesforce_tooling_client = Restforce.tooling(...)

@salesforce_tooling_client.create!("CustomField", {
  "FullName" => "Account.my_namespace__my_custom_field_name__c",
  "Metadata" => {
    type: "Text",
    label: "This is my label",
    length: 255,
    required: 'false',
    unique: 'false',
    externalId: 'false',
    trackHistory: 'false'
   }
})
```
But I can't update the field like this...
```
@salesforce_client = Restforce.new(...)

salesforce_account = @salesforce_client.create('Account', Name: 'ABC')

@salesforce_client.update(
  'Account',
  Id: salesforce_account.Id,
  "my_namespace__my_custom_field_name__c": 123
)
```
until after I go into the Salesforce Web UI and make the field's accessibility "Editable" like this:
![screen shot 2018-01-03 at 1 33 38 pm](https://user-images.githubusercontent.com/1825103/34534064-c8c39240-f08a-11e7-841d-5b9a35573a58.png)

Any help is greatly appreciated!

**Comment by timrogers** [comment]
I think it might be possible with the Metadata API - see https://salesforce.stackexchange.com/questions/36846/metadata-api-custom-field-permissions-how-to-automate-this-process/64743 - but it looks like it's difficult. I'm going to close this issue, as it's out-of-scope for Restforce.

**Comment by LucasCioffi** [comment]
@timrogers Thank you for that prompt response.

Just to make sure I'm not missing anything, 

1. With this gem we can create custom fields via the Tooling API, but we cannot update the value of that field for any record in Salesforce?

2. And this gem does not deal with the Metadata API?

Once again, I do appreciate it.

**Comment by timrogers** [comment]
1. Yes, that's right, as far as I'm aware.
2. Yes.

**Comment by LucasCioffi** [comment]
@timrogers I was able to use the Metaforce gem to create a permission set and then update that permission set so that the custom field is editable.
```
@salesforce_metadata_client.create_metadata(:permission_set, full_name: 'ABC', label: 'ABC')

@salesforce_metadata_client.update_metadata(
  :permission_set, fullName: 'ABC', label: 'ABC', fieldPermissions:
  [field: "Account.#{salesforce_namespace}__#{custom_field_name}__c",
  editable: true, readable: true]
)
```

Can I use this Restforce gem to assign the permission set to a Salesforce user?  Here is the relevant page from the SOAP API Developer Guide: https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_permissionsetassignment.htm

**Comment by LucasCioffi** [comment]
@timrogers I got the answer for how to assign a permission set to a user.  Here it is in case it's helpful for others in the future:
```
current_user_salesforce_id = @current_user.salesforce_uid.split('/')[-1]

permission_set_id = @salesforce_client.query("SELECT Id FROM PermissionSet WHERE Name='Name_of_my_permission_set'").first.Id

@salesforce_client.create(
  'PermissionSetAssignment', AssigneeId: current_user_salesforce_id,
  PermissionSetId: permission_set_id
)
```

**Comment by jclusso** [comment]
So I'm not sure I'm following here. Also confused about how you use the metaforce gem with OAuth. 

Is there really no way to create a custom field with tooling API that is accessible after being created without editing the field security within the panel?
