### ISSUE TITLE
iterating over the Restforce::Collection

### ISSUE THREAD

**Issue by okram999** [restforce/restforce#354]
how can i access the "records" array in the object that i got by quering an sf instance? `accounts = client.query('select Id, EventType, Logdate from EventLogFile where LogDate = 2018-01-01T00:00:00Z')`

**Comment by timrogers** [comment]
Is `records` a field on the `EventLogFile`?

**Comment by okram999** [comment]
no, record is not a field in the EventLogFile.  This is the response as the 'accounts' in the question. 

`#<Restforce::Collection:0x00000002197218 @client=#<Restforce::Data::Client @options={:api_version=>"41.0", :username=>"sfdc.dev", :password=>"somepass!", :security_token=>nil, :client_id=>"3MVG9A2kN3Bn1XgTalsb2qZ0e7r9tzLavy7o_V7AAQG7jKctPLq.qDq", :client_secret=>"87623", :host=>"login.salesforce.com", :oauth_token=>"DIZcbAJBBdKtF67Vm3pBI1vasRBp41PQpDCz2yfghnqwXYpyvcecLvpUx", :refresh_token=>nil, :instance_url=>"https://myorg.my.salesforce.com", :cache=>nil, :authentication_retries=>3, :compress=>nil, :mashify=>nil, :timeout=>nil, :adapter=>:net_http, :proxy_uri=>nil, :authentication_callback=>nil, :ssl=>{}, :request_headers=>nil, :logger=>#<Logger:0x00000002158158 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000021580e0 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00000002158068 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00000002158798>>>, :log_level=>:debug}>, @raw_page={"totalSize"=>2, "done"=>true, "records"=>[{"attributes"=>{"type"=>"Account", "url"=>"/services/data/v41.0/sobjects/Account/001i000002EF7iDAAT"}, "Id"=>"001i000002EF7iDAAT", "Name"=>"Sterlidge Pty Ltd", "AccountNumber"=>nil}, {"attributes"=>{"type"=>"Account", "url"=>"/services/data/v41.0/sobjects/Account/001i000002EF7iEAAT"}, "Id"=>"001i000002EF7iEAAT", "Name"=>"Sherwood Gem Pty Ltd", "AccountNumber"=>nil}]}>`

**Comment by okram999** [comment]
okay - i think i got this, i looked into the source https://github.com/restforce/restforce/blob/master/lib/restforce/collection.rb

```
accounts.each do |i|
    puts i.EventType 
    puts i.Id
    puts i.LogDate    
end
```

**Comment by antwonlee** [comment]
@okram999 Did you find a solution to this?  Also, when you are talking about :oauth_token, are you referring to this? `:oauth_token=>"DIZcbAJBBdKtF67Vm3pBI1vasRBp41PQpDCz2yfghnqwXYpyvcecLvpUx"` from your response?

**Comment by okram999** [comment]
yes, and i found the way to get that from the api docs
