### ISSUE TITLE
Invalid_grant: authentication failure

### ISSUE THREAD

**Issue by aureo96** [restforce/restforce#357]
Hello so before having this issue I was able to update my sandbox tables using the following code to retrieve the token:
```

restforce_client = Restforce.new(username: ENV['SALESFORCE_USERNAME'],

                                      password: ENV['SALESFORCE_PASSWORD'],

                                      security_token: ENV['SALESFORCE_SECURITY_TOKEN'],

                                      client_id: ENV['SALESFORCE_CLIENT_ID'],

                                      client_secret: ENV['SALESFORCE_CLIENT_SECRET'],

                                      api_version: ENV['SALESFORCE_API_VERSION'])
```

However, After Christmas break I only get this error. I change my password and security token and added them to my project, but I still get this error. I looked at the login history, in salesforce, and it seems the call is hitting the user, but the access is denied due to "Invalid Password". Is someone currently experiencing this or has solve this issue?

**Comment by okram999** [comment]
how about checking the `clientId` and the `client secret` for the connected app?
i am using it and it still works.

**Comment by aureo96** [comment]
@okram999 Yeah those are fine. I even created a new connected app and copy pasted the client secret/Id. However, I am still unable to connect. 
In the login history it even tells me that it was my connected app which had the Invalid Password.

**Comment by okram999** [comment]
ok. Below are some things that you can do to isolate the issue:

1. make sure you are using the version: **restforce (2.5.3)** [this is what i use and commenting based on it]
2. Try using your credentials with the ant migration tool. This will make sure your login credentials work.
3. Silly but, make sure there is no typos in there.  The log` access is denied due to "Invalid Password"`, still says your issue is local to your env.

**Comment by aureo96** [comment]
Yeah something is wrong here:
![image](https://user-images.githubusercontent.com/25411302/34912705-66819124-f8ad-11e7-8f1f-1b3dc06e320e.png)

**Comment by aureo96** [comment]
@okram999 is the migration tool considered a Third-Party Account, because my Third-Party Account List in settings shows as disabled.

**Comment by antwonlee** [comment]
If all your credential seems right, but still not able to login—try unlocking the user.  It might be locked due to multiple login failure attempts.

**Comment by aureo96** [comment]
@antwonlee It does not seem to be that. As far as I can see all my users are marked as active. I already asked my Product Owner to request recent login attempts, in order to see the credentials that were used. From there  I will see what I can do. Thanks Anyways.

I will give a follow up once I get what I requested.

**Comment by antwonlee** [comment]
Do you have another **working** username/password credentials you can test?

**Comment by aureo96** [comment]
@antwonlee @okram999 So apparently my product owner sent me an old security token when I asked him to send me the most recent. I guess this would have been solved earlier if I had reset the security token, but I did not want to wait until the reply. Thus, I asked him for the most recent one, and got the right one.

Sorry for opening an issue that was not due to the gem or salesforce itself.

**Comment by aaronromeo** [comment]
I had to make the following change in my Salesforce settings for _Permitted Users_.
![screen shot 2018-12-05 at 4 24 43 pm](https://user-images.githubusercontent.com/1504710/49545048-84be6880-f8aa-11e8-9fec-5f65771ed6eb.png)

`authenticate!` worked fine after that. 

In my case I am hitting the developer environment. so these are my settings.
```
    def initialize
      @client = Restforce.new(
        api_version: '44.0',
        username: ENV['SALESFORCE_USERNAME'],
        password: ENV['SALESFORCE_PASSWORD'],
        security_token: ENV['SALESFORCE_SECURITY_TOKEN'],
        client_id: ENV['SALESFORCE_CONSUMER_KEY'],
        client_secret: ENV['SALESFORCE_CONSUMER_SECRET'],
      )
    end
```
