### ISSUE TITLE
Posting on chatter with restforce

### ISSUE THREAD

**Issue by okram999** [restforce/restforce#361]
can i use restforce to do a simple chatter post?

**Comment by antwonlee** [comment]
I don't think so. https://github.com/restforce/restforce/issues/38

**Comment by antwonlee** [comment]
As well as https://github.com/restforce/restforce/issues/83

**Comment by timrogers** [comment]
You can! I've done it in the past. You'll want to create a `FeedItem` - see https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_responses_feed_item.htm for the attributes. The code will look like:

```ruby
client.create('FeedItem', attributes)
```

**Comment by antwonlee** [comment]
Ah!  Thanks @timrogers Sorry @okram999!

**Comment by okram999** [comment]
thanks @antwonlee and @timrogers
