### ISSUE TITLE
Sporadic connection prefix + authentication failure (using Middleware::Authentication::Password)

### ISSUE THREAD

**Issue by inoda** [restforce/restforce#367]
I am experiencing sporadic Authorization/Authentication exceptions. `UnauthorizedErrorConnection: Connection prefix not set` is always raised first, followed by `AuthenticationError: invalid_grant: authentication failure`. 

`Restforce::UnauthorizedError: Connection prefix not set`
https://github.com/restforce/restforce/blob/master/lib/restforce/middleware/instance_url.rb#L7

`Restforce::AuthenticationError: invalid_grant: authentication failure`
https://github.com/restforce/restforce/blob/master/lib/restforce/middleware/authentication.rb#L28

I don't understand why `url_prefix_set?` would sometimes return false.

Here is my Restforce config:
```
Restforce.configure do |config|
  # The following config is pulled in automatically from ENV vars:
  # SALESFORCE_USERNAME
  # SALESFORCE_PASSWORD
  # SALESFORCE_SECURITY_TOKEN
  # SALESFORCE_CLIENT_ID
  # SALESFORCE_CLIENT_SECRET

  config.host = ENV['SALESFORCE_GATEWAY']  # login.salesforce.com
  config.api_version = 29.0
end
```

Thank you for working on this library, and please let me know if there is any additional information you need from me!

**Comment by JaisonBrooks** [comment]
I am having this issue all over the place today. Im using API version 39.0.

**Comment by inoda** [comment]
So we learned this was NOT a Restforce problem. It took getting on the phone w/ a SF rep, but we were hitting our 3600/hr login limit. The error message SF is just really unexplicit. 

We were making the mistake of initializing a Restforce client _per request_, as opposed to once upon server start.

**Comment by SahSantoshh** [comment]
@inoda How did you fix this issue? I am facing same issue. Would you please guid me through this?
