### ISSUE TITLE
User Accounts / Fields won't sync user to new sandbox Error "Provided external ID field does not exist or is not accessible"

### ISSUE THREAD

**Issue by pixelparlordev** [restforce/restforce#376]
Hi. I have been developing with one sandbox with a specific app, and everything was working fine. I was able to sync user info back and forth. Then we switched to a new test sandbox, with the exact same app. Now, for some reason I can't create a new user and sync to salesforce. 

When I try to click add to salesforce as a new user, I get a user name like tmp_sf_5aecbe07d3ca11.77821783

Then I try to push or pull and it has an error that says:

Provided external ID field does not exist or is not accessible: tmp_sf_5aecbe07d3ca11.77821783
 And it says this for everything. For some reason If I were to disconnect and reconnect with the old sandbox I can update info. So I am just wondering if anyone knows what these errors are. 

Mapping error example

Push to Salesforce | 12 | user | tmp_sf_5aecbe07d3ca11.77821783 | 2018-05-04 4:09:43pm 

It seems like it says it's syncing to SF, but it really isn't. I am confused by this. This almost seems like something I should have caught, but it just isn't changing no matter wha I do.

**Comment by pixelparlordev** [comment]
never-mind wrong thing

**Comment by antwonlee** [comment]
@pixelparlordev were you able to solve this problem?  If so, let us know so others can reference this issue later.
