### ISSUE TITLE
undefined method `fetch' for "":String with update to 3.0.0

### ISSUE THREAD

**Issue by abezzub-upstart** [restforce/restforce#396]
We just switched to the latest version of Restforce because of CVE and are now getting this error for all `upsert!` calls:

"undefined method `fetch' for "":String

Error happens on this line:
https://github.com/restforce/restforce/blob/b3a52e8cfcfd20af727b3c8449ffc599774e3035/lib/restforce/concerns/api.rb#L383

**Comment by timrogers** [comment]
This is fixed in #395. I’ll release a patch tomorrow.

**Comment by timrogers** [comment]
Fixed by #395
