### ISSUE TITLE
Login with Sales Force Button

### ISSUE THREAD

**Issue by techsethi** [restforce/restforce#405]
Hi,

It may not be the perfect place to place this query but I want to implement a "Login with Sales Force" button on my button using oAuth or omniauth.

I have looked around but haven't found any solution. Can someone point me to any links / gem to use for the same.

Thanks in advance.

**Comment by antwonlee** [comment]
Hey @techsethi I have made a demo here: https://github.com/antwonlee/restforce-omniauth-salesforce-demo-app

**Comment by antwonlee** [comment]
You will need these gems: https://github.com/antwonlee/restforce-omniauth-salesforce-demo-app/blob/688b3323bd488594dcad22cb2f1accd3eead15a2/Gemfile#L63-L64
