### ISSUE TITLE
.update! creating a new record?

### ISSUE THREAD

**Issue by iandonovan** [restforce/restforce#406]
First off, thanks so much for the library and your work on it, it's appreciated.

My issue is this: I am using username&password authentication, and everything's working great. I can create new Opportunity objects (through `client.create!`) and everything's great. Later, though, I'm retrieving the record and using `.update` to alter it, like this:

```ruby
client.update!(
  "Opportunity",
  Id: [correct id],
  Name: [name],
  # etc . . .
)
```

This operation succeeds, but it creates a new record in the salesforce dashboard! I don't want that. If I use `client.find` with the same ID, it returns the object just fine, so I doubt it's a matter of the ID getting mixed up.

Any thoughts?

**Comment by antwonlee** [comment]
You are right, that shouldn't be.

Few questions.

1. Does it update the original record and create another with same data or does it create new record but does not update the original record?

2. Since you tried with `!`, what exceptions were raised?

Try it without the `!` and see what that does.

```
client.update(
  "Opportunity",
  Id: [correct id],
  Name: [name],
  # etc . . .
)
```

**Comment by iandonovan** [comment]
I feel very silly.

After digging a little deeper, it looks like my code is checking for the resource on salesforce, updating it if it exists, and then _continuing on_ to create a new one, rather than returning. My fault. Oh I'm so embarrassed!!!
