### ISSUE TITLE
How can I get an objects fieldsets?

### ISSUE THREAD

**Issue by SubhaPrince** [restforce/restforce#416]

**Comment by timrogers** [comment]
Can you find a REST API in the Salesforce docs that does this? If so, we should be able to have it in Restforce.

**Comment by SubhaPrince** [comment]
![screen shot 2018-12-03 at 11 26 57](https://user-images.githubusercontent.com/19081810/49355619-6d3a8080-f6ee-11e8-8ee2-46a8e8bf6d98.png)

i can access fieldset by SOQL query by using **tooling api**

**Comment by SubhaPrince** [comment]
Oh thanks i've resolved this issue by using Restforce.tooling..
