### ISSUE TITLE
Restforce.org is down

### ISSUE THREAD

**Issue by Aupajo** [restforce/restforce#540]
Seems to have been down for a few weeks now.

![image](https://user-images.githubusercontent.com/14123/82848954-e57fac00-9f49-11ea-9fd4-13deb4105f8c.png)

**Comment by coffeejunk** [comment]
It looks like the domain expired and has been snagged up by someone else? 

<img width="1318" alt="Screenshot 2020-06-11 12 18 19" src="https://user-images.githubusercontent.com/205556/84374009-ad30cc80-abdd-11ea-99be-fdaaa653f379.png">

cc/ @timrogers

**Comment by timrogers** [comment]
Thanks for reporting this! It's too late sadly, so I have moved to `restforce.github.io`
