### ISSUE TITLE
Unhandled Salesforce error: API_CURRENTLY_DISABLED

### ISSUE THREAD

**Issue by ruipserra** [restforce/restforce#562]
Restforce doesn't have a definition for the error code `API_CURRENTLY_DISABLED`.

This error code is returned when an admin has disabled `API access` in a user profile. [This article](https://support.geckoboard.com/hc/en-us/articles/217148797-How-do-I-enable-API-access-in-Salesforce-) shows where to find this setting.

I discovered this missing error code because:

- [ ] I tried to `rescue` it or refer to it in my code
- [X] I got this error back from Salesforce

**Comment by timrogers** [comment]
I'm almost relieved to see that the effort I went to on those warnings was worth it! Let me fix this now.
