### ISSUE TITLE
v4.x gemspec blocks important Faraday fixes (e.g. can result in zombie TCP connections)

### ISSUE THREAD

**Issue by hongtron** [restforce/restforce#566]
the v4.2.2 gemspec specifies [`gem.add_dependency 'faraday', '<= 1.0', '>= 0.9.0'`](https://github.com/restforce/restforce/blob/v4.2.2/restforce.gemspec#L28), which blocks patch releases of Faraday 1.0. Faraday 1.0.1 has an important fix to prevent TCP connections from being left open: https://github.com/lostisland/faraday/pull/1117

Our ideal solution would be a 4.2.3 release that specifies `'< 1.1'` instead of `'<= 1.0'`. This would unblock our gem version upgrades, which would unblock our upgrade from Ruby 2.4, which would unblock us from upgrading to v5.x of `restforce` 🙂

**Comment by timrogers** [comment]
@hongtron Thanks for reporting this! Can you create a PR for the change?

**Comment by hongtron** [comment]
@timrogers definitely! However, I'm not seeing a v4 branch that I can make a PR against. Do you have a preferred process for pushing updates to past major versions? I don't see any guidelines in `CONTRIBUTING.md`.

**Comment by hongtron** [comment]
@timrogers bump ^^ 🙏🏼

**Comment by hongtron** [comment]
Here's the commit that I'm not able to merge in: https://github.com/hongtron/restforce/commit/d53e88d044cf48ced8d6557225ebad1de774c9c0

**Comment by hongtron** [comment]
Closed via https://github.com/restforce/restforce/pull/622.
