### ISSUE TITLE
Unhandled Salesforce error: SERVER_UNAVAILABLE

### ISSUE THREAD

**Issue by wkirby** [restforce/restforce#568]
Restforce doesn't have a definition for the error code `SERVER_UNAVAILABLE`.

I discovered this missing error code because:

- [X] I tried to `rescue` it or refer to it in my code
- [ ] I got this error back from Salesforce

**Comment by timrogers** [comment]
Thanks for your two issues! I will address these and release a new version in the next 24 hours.

--

Tim Rogers
@timrogers

**Comment by wkirby** [comment]
Awesome, thanks for the fast turnaround.
