### ISSUE TITLE
Unhandled Salesforce error: FIELD_INTEGRITY_EXCEPTION

### ISSUE THREAD

**Issue by taimurdb** [restforce/restforce#578]
Restforce doesn't have a definition for the error code `FIELD_INTEGRITY_EXCEPTION`.

I discovered this missing error code because:

- [ ] I tried to `rescue` it or refer to it in my code
- [x] I got this error back from Salesforce

**Comment by timrogers** [comment]
Fixed by 341ce34f319202c5a64b5b1b2148659f2fbc0be1
