### ISSUE TITLE
Unhandled Salesforce error: JSON_PARSER_ERROR

### ISSUE THREAD

**Issue by nimylian** [restforce/restforce#619]
Restforce doesn't have a definition for the error code `JSON_PARSER_ERROR`.

I discovered this missing error code because:

- [ ] I tried to `rescue` it or refer to it in my code
- [x] I got this error back from Salesforce

sending a String to a Number field, inside of a JSON object
```
Restforce::ResponseError: JSON_PARSER_ERROR: Cannot deserialize instance of double from VALUE_STRING value N010000000 or request may be missing a required field at [line:1, column:507]
```

**Comment by timrogers** [comment]
@nimylian Which version of Restforce are you running? This should be fixed by 9fd33ab4c9c4271704b4a98c2faabf151023e05c which was released as part of `v5.0.4` a few days ago.
