### ISSUE TITLE
"List View Results" response lacks `"totalSize"` property to conform to Restforce::Collection spec

### ISSUE THREAD

**Issue by kwong-yw** [restforce/restforce#706]
The [List View Results](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_listviewresults.htm) REST endpoint returns a response that contains a `"size"` property to indicate the number of records. The `Restforce::Collection` class, on the other hand, defines `size` to be whatever the `totalSize` property is.

This means that in Rails, `list_view_results_response.present?` would return an error `NoMethodError:undefined method 'zero?' for nil:NilClass` as `foo.present?` for Enumerables means `!foo.blank?`, or effectively `!foo.empty?` (which restforce defines as `size.zero?`).

My local workaround for now was to do `foo.instance_variable_get('@raw_page')['size']`, but I'm wondering if a workable solution would be to redefine `Collection#size` to:

```ruby
# Not all Restforce::Collections have a 'totalSize' property, e.g. the listviews results endpoint
# only has a size property.
def size
  @raw_page['totalSize'] || @raw_page['size']
end
alias_method :length, :size
```

If this looks to be a suitable fix I could open a PR to support this change.

**Comment by timrogers** [comment]
@kwong-yw This sounds good to me. How about you create a PR? 🙏
