### ISSUE TITLE
timeout config

### ISSUE THREAD

**Issue by metapraveen** [restforce/restforce#715]
How to configure the timeout when creating restforce client? 

sorry, if I am missing something but I am getting frequent timeout errors. I want to be sure restforce waits till the salesforce api times out. Could not find what is the max time salesforce rest api waits here though https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_rest.htm

**Comment by taf2** [comment]
@metapraveen you can set a timeout like this:

```ruby
Restforce.new(timeout: your_timeout_here)
```

It might be necessary in your case to retry on timeout...
