### ISSUE TITLE
Include response body for CompositeAPIError

### ISSUE THREAD

**Issue by shravan097** [restforce/restforce#766]
### Issue
I have a use case where I want to process the error myself while using `allOrNone` parameters in Composite API. Currently Restforce Composite API will always throw error (if error occurs) when `allOrNone: true` &  throws only error code of the last sub request. 

### Proposal
Include Faraday's response as part of the `CompositeAPIError`. 
PR - https://github.com/restforce/restforce/pull/765

**Comment by timrogers** [comment]
Fixed by #765.
