### ISSUE TITLE
Breaking with ruby 3.2.0

### ISSUE THREAD

**Issue by olafura** [restforce/restforce#775]
Ruby seems to have changed the argument behavior which causes 120 failures in the test suite.

**Comment by olafura** [comment]
This is the first breaking change:
https://github.com/ruby/ruby/commit/752c3dad989bb66e4be61911a82fed992067bdc3

**Comment by suwyn** [comment]
Appears [the issue](https://github.com/lostisland/faraday/issues/1479) is upstream in Faraday.   

[Test pass](https://github.com/suwyn/restforce/actions/runs/3943027449/jobs/6747382235) with Faraday = 1.10 or >= 2.0.1 

The version can be specified by setting the env var `FARADAY_VERSION` before bundle installing, which is what we did.

**Comment by timrogers** [comment]
I've created a PR with an upstream fix to Faraday: https://github.com/lostisland/faraday/pull/1483. As @suwyn says, this issue only seems to affect Faraday v1.x.

**Comment by olafura** [comment]
Thank you @timrogers that did the trick
