### ISSUE TITLE
Unhandled Salesforce error: InvalidMarkup

### ISSUE THREAD

**Issue by spurton** [restforce/restforce#807]
Restforce doesn't have a definition for the error code `InvalidMarkup` and it's error message returned from Chatter API.

I discovered this missing error code because:

- [x] I tried to `rescue` it or refer to it in my code
- [x] I got this error back from Salesforce

**Comment by spurton** [comment]
@timrogers I have a few of these Chatter API-related errors. I can create Issues for each or open a PR to add them... Whichever makes the most sense?

**Comment by spurton** [comment]
I opened [this PR](https://github.com/restforce/restforce/pull/808) to address the remaining errors for Chatter API.

**Comment by timrogers** [comment]
Fixed by #808.
