### ISSUE TITLE
Unhandled Salesforce error: APEX_REST_SERVICES_DISABLED

### ISSUE THREAD

**Issue by Rodrigo-Cardoso** [restforce/restforce#849]
Restforce doesn't have a definition for the error code `APEX_REST_SERVICES_DISABLED`.

I discovered this missing error code because:

- [x] I tried to `rescue` it or refer to it in my code (Restforce::ErrorCode::ApexRestServicesDisabled) 
- [ ] I got this error back from Salesforce

**Comment by Rodrigo-Cardoso** [comment]
Thank you @timrogers 
QQ would it be possible to retroactively add this to v5.3.x and, to that end, v6.2.x?

**Comment by timrogers** [comment]
That's definitely a possibility. Let me have a think about it and get back to you.
