### ISSUE TITLE
Version 7.x requires faraday 2.x

### ISSUE THREAD

**Issue by DheenadhayalanG** [restforce/restforce#884]
Restforce 7.x doesn't work with 1.9.3. **Please update your gem dependency**

I discovered this error by executing the below code.

Version restforce 7.3.1,   faraday 2.7.4
```
Salesforce::Client.new.list_accounts
# => Received result
```

Version restforce 6.2.3, faraday 1.9.3
```
Salesforce::Client.new.list_accounts
ArgumentError: wrong number of arguments (given 2, expected 0..1)
```

**Comment by timrogers** [comment]
Hi there! 👋 

The gemspec for v7.0.0 onwards says that only Ruby 3.0+ is supported: https://github.com/restforce/restforce/blob/v7.0.0/restforce.gemspec

The readme also states that you must use v2.4.2 for Ruby 1.9.3:

> As of version 7.0.0, this gem is only compatible with Ruby 3.0.0 and later. If you're using an earlier Ruby version:
>
> * ...
> * for Ruby 1.9.3, use version 2.4.2

Is there somewhere specific where you see wrong information?

**Comment by DheenadhayalanG** [comment]
I was using Ruby 3.2.2, Faraday 1.9.3, restforce 6.2.3, And the application is working fine.

When i tried to upgrade restforce 7.x. Started getting exception `wrong number of arguments (given 2, expected 0..1)`.

It might be good to **change the runtime dependency of faraday** to exact working version. 

Please find the faraday runtime dependency version on screenshot.

<img width="769" alt="image" src="https://github.com/restforce/restforce/assets/127303350/08767760-02d7-4751-b6c3-13e7ce0b9421">

**Comment by DheenadhayalanG** [comment]
Got it.
It didnt forced for updated version of faraday required version while doing `bundle install`

No issues.
