### ISSUE TITLE
Unable to tag users using restforce 'FeedItem'

### ISSUE THREAD

**Issue by aalejandromr** [restforce/restforce#896]
Hey, I'm wondering if I'm doing something wrong while trying to post a feed item to tag a user. In Salesforce, I have a custom object called "Account". I want to post a feed item in the Account's chatter, tagging a user so a notification is triggered. The following [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_action.meta/api_action/actions_obj_post_to_chatter.htm) mentions that I should be able to tag a user if I do the following format: `@[user ID]`; however, using the rest force gem, the chatter message ends up being the literal ID string instead. For example, for a user's ID "005000000000001" the chatter feed item is posted successfully but with the following string "From console @[005000000000001]" instead of "From console @aalejandromr"

Any ideas why? This is the piece of code I'm using

```
client = Restforce.new
chatter_message = "From console @[#{mentioned_user_id}]"
begin
    client.create!('FeedItem', ParentId: account_sfid, Body: chatter_message)
    puts "FeedItem created successfully"
rescue StandardError => e
    puts "An error occurred: #{e.message}"
end

>> "FeedItem created successfully"
nil
```

It is worth mentioning that in Salesforce, I've logged in using the salesforce user used by Restforce, and it can tag any user.

**Comment by aalejandromr** [comment]
Api version for Salesforce I'm using is `59.0`

**Comment by timrogers** [comment]
I believe the API you linked is a different one to the once you're using by calling `client.create!('FeedItem', **args)`. You're using the create call for the `FeedItem` object documented [here](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_feeditem.htm), and this tagging thing doesn't seem to be mentioned there.

**Comment by aalejandromr** [comment]
@timrogers, ah, that makes sense! Do you know how to use the "Post to chatter" action? Is that something possible with restforce?

**Comment by timrogers** [comment]
I'm afraid that I don't know exactly. I don't believe Chatter is directly integrated, but Restforce does have primitives to help you interact the Salesforce API with low-level requests.

You can make direct requests using `Restforce#get` and similar methods (see example [here](https://github.com/restforce/restforce?tab=readme-ov-file#custom-apex-rest-endpoints)) and use that to hit the Chatter API.

I'd be willing to accept a contribution if you write that code and want to contribute it back upstream 😊

**Comment by aalejandromr** [comment]
Thanks for the help @timrogers - I got some inspiration from [this post](https://salesforce.stackexchange.com/questions/1545/how-can-i-add-an-mention-when-creating-a-feeditem-via-apex) and was able to create a chatter feed item with the ability to tag. The implementation looks like this using message segments.

```
message_segments = [
  {
    "type": "Text",
    "text": "Chatter message from Rails console "
  },
  {
    "type": "Mention",
    "id": mentioned_user_id
  }
]

  response = restforce_client.post("/services/data/v53.0/chatter/feed-elements", {
    "body": {
      "messageSegments": message_segments
    },
    "feedElementType": "FeedItem",
    "subjectId": parent_sfid
  })
  ```
